# Generated by Django 3.2 on 2023-11-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbooking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
