# Generated by Django 3.2 on 2023-11-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbooking', '0002_alter_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookhere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=50, unique=True)),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_number', models.IntegerField()),
                ('receiver_name', models.CharField(max_length=100)),
                ('receiver_number', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
