# Generated by Django 3.2 on 2023-11-27 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbooking', '0003_bookhere'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookhere',
        ),
    ]
